name: E2EMatrixTrigger
on:
  schedule:
    - cron: '7 */8 * * *'
  push:
    branches:
      - 'main'
  workflow_run:
    workflows:
      - ApprovalComment
    types:
      - completed
  workflow_dispatch:
    inputs:
      region:
        required: true
        default: 'us-east-2'
        type: choice
        options:
          - "us-east-1"
          - "us-east-2"
          - "us-west-2"
          - "eu-west-1"
      cleanup:
        required: true
        default: true
        type: boolean
      cidr_block:
        required: true
        type: string
        default: '192.168.0.0/16'
jobs:
  resolve:
    if: (github.repository == 'aws/karpenter-provider-aws' && (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success')) || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/resolve-args.yaml
    with:
      allowed_comment: "snapshot"
  private-cluster-trigger:
    permissions:
      id-token: write # aws-actions/configure-aws-credentials@v4.0.1
      statuses: write # ./.github/actions/commit-status/start
    needs: [resolve]
    if: needs.resolve.outputs.SHOULD_RUN == 'true'
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: Integration
      git_ref: ${{ needs.resolve.outputs.GIT_REF }}
      region: ${{ inputs.region || 'us-east-2' }}
      workflow_trigger: "private_cluster"
      # Default to true unless using a workflow_dispatch
      cleanup: ${{ github.event_name != 'workflow_dispatch' && true || inputs.cleanup }}
      cidr_block: ${{ inputs.cidr_block || '192.168.0.0/16' }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
